export const CONFIDENCE_BEHAVIOR_OBSERVED = 0.15;
export const CONFIDENCE_REPEATED_EVIDENCE = 0.35;
export const CONFIDENCE_PATTERN_DETECTED = 0.6;
export const CONFIDENCE_HABIT_ESTABLISHED = 0.8;
export const CONFIDENCE_HABIT_EVOLVES = 0.85;
export const CONFIDENCE_HABIT_WEAKENS = 0.45;
export const CONFIDENCE_HABIT_ARCHIVED = 0.2;
export const CONFIDENCE_HABIT_VERIFIED = 1.0;
