import { eventService } from "../events/event-service";
import { MemoryEvent } from "../events/types";
import { MemoryCandidate } from "./candidate";
import { rules } from "./candidate-rules";

export type CandidateListener = (candidate: MemoryCandidate) => void;
const listeners = new Set<CandidateListener>();

// In-memory array cache for keeping track of candidates generated during runtime
const candidateHistory: MemoryCandidate[] = [];

const uid = () =>
  typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : Math.random().toString(36).slice(2) + Date.now().toString(36);

export const candidateService = {
  /**
   * Subscribe to new candidates being generated by the system.
   * Useful for downstream validation, triggers, or logging.
   */
  subscribe(listener: CandidateListener): () => void {
    listeners.add(listener);
    return () => {
      listeners.delete(listener);
    };
  },

  /**
   * Retrieve in-memory cache of memory candidates generated since application load.
   */
  getCandidates(): MemoryCandidate[] {
    return candidateHistory;
  },

  /**
   * Clear the candidates history log.
   */
  clearHistory(): void {
    candidateHistory.length = 0;
  },

  /**
   * Evaluate a raw event and generate a candidate memory if matching rules are satisfied.
   */
  evaluateEvent(event: MemoryEvent): MemoryCandidate | null {
    for (const rule of rules) {
      const result = rule.evaluate(event);
      if (result.shouldGenerate && result.reason && result.explanation) {
        const candidate: MemoryCandidate = {
          id: uid(),
          sourceEventId: event.id,
          timestamp: new Date().toISOString(),
          reason: result.reason,
          explanation: result.explanation,
          title: event.title,
          description: event.description,
          relatedProjectId: event.relatedProjectId,
          relatedNoteId: event.relatedNoteId,
          metadata: event.metadata,
        };

        candidateHistory.unshift(candidate);
        listeners.forEach((listener) => {
          try {
            listener(candidate);
          } catch (err) {
            console.error("Error executing candidate subscription listener:", err);
          }
        });

        return candidate;
      }
    }
    return null;
  },

  /**
   * Initialize Event Service subscription.
   */
  initialize(): void {
    if (!eventSub) {
      eventSub = eventService.onRecord((event) => {
        this.evaluateEvent(event);
      });
    }
  },

  /**
   * Dispose Event Service subscription to avoid memory leaks.
   */
  dispose(): void {
    if (eventSub) {
      eventSub();
      eventSub = null;
    }
  },
};

let eventSub: (() => void) | null = null;

// Automatic integration: initialize by default on load
candidateService.initialize();
