import { PermissionDescriptor } from "./permission";

/**
 * Built‑in permission catalog.
 * All platform permissions are defined here and registered once during runtime startup.
 */
export const PermissionCatalog: PermissionDescriptor[] = [
  {
    id: "workspace.read",
    name: "Workspace Read",
    description: "Read access to workspace data",
    group: "Workspace",
    scope: "Read",
    riskLevel: "Low",
    defaultGrant: false,
  },
  {
    id: "workspace.write",
    name: "Workspace Write",
    description: "Write access to workspace data",
    group: "Workspace",
    scope: "Write",
    riskLevel: "Medium",
    defaultGrant: false,
  },
  {
    id: "timeline.read",
    name: "Timeline Read",
    description: "Read access to timeline entries",
    group: "Timeline",
    scope: "Read",
    riskLevel: "Low",
    defaultGrant: false,
  },
  {
    id: "timeline.write",
    name: "Timeline Write",
    description: "Write access to timeline entries",
    group: "Timeline",
    scope: "Write",
    riskLevel: "Medium",
    defaultGrant: false,
  },
  {
    id: "analytics.read",
    name: "Analytics Read",
    description: "Read analytics data",
    group: "Analytics",
    scope: "Read",
    riskLevel: "Low",
    defaultGrant: false,
  },
  {
    id: "analytics.write",
    name: "Analytics Write",
    description: "Write analytics data",
    group: "Analytics",
    scope: "Write",
    riskLevel: "High",
    defaultGrant: false,
  },
  {
    id: "storage.read",
    name: "Storage Read",
    description: "Read from persistent storage",
    group: "Storage",
    scope: "Read",
    riskLevel: "Low",
    defaultGrant: false,
  },
  {
    id: "storage.write",
    name: "Storage Write",
    description: "Write to persistent storage",
    group: "Storage",
    scope: "Write",
    riskLevel: "Medium",
    defaultGrant: false,
  },
  {
    id: "memory.read",
    name: "Memory Read",
    description: "Read from in‑memory structures",
    group: "Memory",
    scope: "Read",
    riskLevel: "Low",
    defaultGrant: false,
  },
  {
    id: "memory.write",
    name: "Memory Write",
    description: "Write to in‑memory structures",
    group: "Memory",
    scope: "Write",
    riskLevel: "Medium",
    defaultGrant: false,
  },
  {
    id: "notifications.read",
    name: "Notifications Read",
    description: "Read notification settings and history",
    group: "Notifications",
    scope: "Read",
    riskLevel: "Low",
    defaultGrant: false,
  },
  {
    id: "notifications.send",
    name: "Notifications Send",
    description: "Send notifications to the user",
    group: "Notifications",
    scope: "Execute",
    riskLevel: "Medium",
    defaultGrant: false,
  },
  {
    id: "voice.listen",
    name: "Voice Listen",
    description: "Access microphone input",
    group: "Voice",
    scope: "Read",
    riskLevel: "High",
    defaultGrant: false,
  },
  {
    id: "voice.speak",
    name: "Voice Speak",
    description: "Emit audio output via TTS",
    group: "Voice",
    scope: "Execute",
    riskLevel: "Low",
    defaultGrant: false,
  },
  {
    id: "search.query",
    name: "Search Query",
    description: "Perform search operations",
    group: "Search",
    scope: "Execute",
    riskLevel: "Low",
    defaultGrant: false,
  },
  {
    id: "system.admin",
    name: "System Admin",
    description: "Full administrative control over the platform",
    group: "System",
    scope: "Admin",
    riskLevel: "Critical",
    defaultGrant: false,
  },
];
