import type { AkiraState, Project } from "./akira-store";

const uid = () =>
  typeof crypto !== "undefined" && "randomUUID" in crypto
    ? crypto.randomUUID()
    : Math.random().toString(36).slice(2) + Date.now().toString(36);

const nowISO = () => new Date().toISOString();

export function seed(): AkiraState {
  const yesterdayISO = (hour: number, minute = 0) => {
    const d = new Date();
    d.setDate(d.getDate() - 1);
    d.setHours(hour, minute, 0, 0);
    return d.toISOString();
  };

  const lovshik: Project = {
    id: uid(),
    name: "Lovshik 2.0",
    tag: "Personal OS",
    description: "The operating system for the next version of myself.",
    progress: 72,
    color: "from-violet to-electric",
    nextTask: "Define identity pillars for v2",
    notes: "Focus areas: health, craft, capital, relationships.",
    timeSpentMinutes: 1340,
    lastWorked: nowISO(),
    createdAt: nowISO(),
    icon: "rocket",
  };
  const akiraP: Project = {
    id: uid(),
    name: "AKIRA",
    tag: "AI Companion",
    description: "A premium AI operating system for personal growth.",
    progress: 41,
    color: "from-electric to-cyan-glow",
    nextTask: "Wire frontend MVP through service layer",
    notes: "Keep the design language. Mock data only for now.",
    timeSpentMinutes: 520,
    lastWorked: nowISO(),
    createdAt: nowISO(),
    icon: "cpu",
  };
  const verilog: Project = {
    id: uid(),
    name: "Verilog CPU",
    tag: "Hardware",
    description: "Designing a RISC-V core on a custom FPGA board.",
    progress: 25,
    color: "from-violet to-cyan-glow",
    nextTask: "Verify instruction cache register maps",
    notes: "Review ALU flags. Need custom assembler compiler scripts.",
    timeSpentMinutes: 240,
    lastWorked: nowISO(),
    createdAt: nowISO(),
    icon: "cpu",
  };

  return {
    projects: [lovshik, akiraP, verilog],
    tasks: [
      {
        id: uid(),
        title: "Define identity pillars for v2",
        description: "Review value framework and core drivers.",
        priority: "High",
        estimatedDuration: 45,
        done: false,
        completed: false,
        projectId: lovshik.id,
        createdAt: nowISO(),
        updatedAt: nowISO(),
      },
      {
        id: uid(),
        title: "Walk 6km zone 2",
        description: "Keep heart rate between 120-130bpm.",
        priority: "Medium",
        estimatedDuration: 60,
        done: true,
        completed: true,
        projectId: lovshik.id,
        createdAt: nowISO(),
        updatedAt: nowISO(),
      },
      {
        id: uid(),
        title: "Read 20 pages of Antifragile",
        description: "Highlight key paragraphs on option payoffs.",
        priority: "Low",
        estimatedDuration: 30,
        done: true,
        completed: true,
        projectId: lovshik.id,
        createdAt: nowISO(),
        updatedAt: nowISO(),
      },
      {
        id: uid(),
        title: "Ship AKIRA AI Core animation",
        description: "Concentric orbit particles with canvas fade.",
        priority: "High",
        estimatedDuration: 120,
        done: true,
        completed: true,
        projectId: akiraP.id,
        createdAt: nowISO(),
        updatedAt: nowISO(),
      },
      {
        id: uid(),
        title: "Wire frontend MVP through service layer",
        description: "Refactor router to load store state values.",
        priority: "Medium",
        estimatedDuration: 90,
        done: false,
        completed: false,
        projectId: akiraP.id,
        createdAt: nowISO(),
        updatedAt: nowISO(),
      },
      {
        id: uid(),
        title: "Verilog ALU overflow tests",
        description: "Verify flags under standard signed overflows.",
        priority: "High",
        estimatedDuration: 45,
        done: true,
        completed: true,
        projectId: verilog.id,
        createdAt: nowISO(),
        updatedAt: nowISO(),
      },
      {
        id: uid(),
        title: "Verify signed overflow registers",
        description: "Perform register comparisons on arithmetic limits.",
        priority: "Medium",
        estimatedDuration: 30,
        done: true,
        completed: true,
        projectId: verilog.id,
        createdAt: nowISO(),
        updatedAt: nowISO(),
      },
      {
        id: uid(),
        title: "Verify instruction cache register maps",
        description: "Configure mapping routines in FPGA registers.",
        priority: "Low",
        estimatedDuration: 45,
        done: false,
        completed: false,
        projectId: verilog.id,
        createdAt: nowISO(),
        updatedAt: nowISO(),
      },
    ],
    notes: [
      {
        id: uid(),
        title: "AKIRA Reflection Idea",
        content: "Every project should have a reflection log where I track my state.",
        tags: ["ideas", "akira"],
        pinned: true,
        favorite: true,
        projectId: akiraP.id,
        createdAt: nowISO(),
        updatedAt: nowISO(),
      },
      {
        id: uid(),
        title: "Decaying Streaks Concept",
        content: "Instead of losing streaks entirely, make them decay over time.",
        tags: ["design", "habits"],
        pinned: false,
        favorite: true,
        projectId: null,
        createdAt: nowISO(),
        updatedAt: nowISO(),
      },
      {
        id: uid(),
        title: "Voice-First Daily Mission",
        content: "What if daily missions could be declared by voice capture?",
        tags: ["voice", "ideas"],
        pinned: false,
        favorite: false,
        projectId: null,
        createdAt: nowISO(),
        updatedAt: nowISO(),
      },
    ],
    chat: [
      {
        id: uid(),
        role: "akira",
        text: "I am AKIRA. Ready to deploy your companion modules.",
        createdAt: nowISO(),
      },
    ],
    streaks: [
      {
        id: uid(),
        label: "AKIRA",
        icon: "sparkles",
        days: 12,
        pct: 95,
        color: "from-violet to-electric",
      },
      {
        id: uid(),
        label: "Fitness",
        icon: "dumbbell",
        days: 8,
        pct: 85,
        color: "from-electric to-cyan-glow",
      },
      {
        id: uid(),
        label: "Deep Craft",
        icon: "cpu",
        days: 5,
        pct: 90,
        color: "from-violet to-cyan-glow",
      },
      {
        id: uid(),
        label: "Reading",
        icon: "book",
        days: 15,
        pct: 100,
        color: "from-cyan-glow to-electric",
      },
      {
        id: uid(),
        label: "Sleep",
        icon: "moon",
        days: 21,
        pct: 80,
        color: "from-cyan-glow to-electric",
      },
    ],
    profile: { name: "Lovshik", role: "Founder · Engineer", motto: "Building Lovshik 2.0" },
    lastProjectId: akiraP.id,
    memories: [
      {
        id: uid(),
        timestamp: yesterdayISO(9, 30),
        eventType: "note_created",
        title: "Note Created",
        description: 'Captured thought: "AKIRA Reflection Idea"',
        metadata: { title: "AKIRA Reflection Idea" },
      },
      {
        id: uid(),
        timestamp: yesterdayISO(9, 45),
        eventType: "note_created",
        title: "Note Created",
        description: 'Captured thought: "Decaying Streaks Concept"',
        metadata: { title: "Decaying Streaks Concept" },
      },
      {
        id: uid(),
        timestamp: yesterdayISO(16, 0),
        eventType: "note_created",
        title: "Note Created",
        description: 'Captured thought: "Voice-First Daily Mission"',
        metadata: { title: "Voice-First Daily Mission" },
      },
      {
        id: uid(),
        timestamp: yesterdayISO(10, 15),
        eventType: "task_completed",
        title: "Task Completed",
        description: 'Completed task: "Ship AKIRA AI Core animation"',
        metadata: { title: "Ship AKIRA AI Core animation" },
      },
      {
        id: uid(),
        timestamp: yesterdayISO(14, 10),
        eventType: "task_completed",
        title: "Task Completed",
        description: 'Completed task: "Verilog ALU overflow tests"',
        metadata: { title: "Verilog ALU overflow tests" },
      },
      {
        id: uid(),
        timestamp: yesterdayISO(14, 15),
        eventType: "task_completed",
        title: "Task Completed",
        description: 'Completed task: "Verify signed overflow registers"',
        metadata: { title: "Verify signed overflow registers" },
      },
      {
        id: uid(),
        timestamp: yesterdayISO(18, 0),
        eventType: "task_completed",
        title: "Task Completed",
        description: 'Completed task: "Walk 6km zone 2"',
        metadata: { title: "Walk 6km zone 2" },
      },
      {
        id: uid(),
        timestamp: yesterdayISO(21, 30),
        eventType: "task_completed",
        title: "Task Completed",
        description: 'Completed task: "Read 20 pages of Antifragile"',
        metadata: { title: "Read 20 pages of Antifragile" },
      },
      {
        id: uid(),
        timestamp: yesterdayISO(10, 0),
        eventType: "project_continued",
        title: "Project Continued",
        description: "Resumed work on: AKIRA",
        relatedProjectId: akiraP.id,
        metadata: { name: "AKIRA" },
      },
      {
        id: uid(),
        timestamp: yesterdayISO(14, 0),
        eventType: "project_continued",
        title: "Project Continued",
        description: "Resumed work on: Verilog CPU",
        relatedProjectId: verilog.id,
        metadata: { name: "Verilog CPU" },
      },
    ],
    sessions: [
      {
        id: uid(),
        projectId: akiraP.id,
        task: "Ship AKIRA AI Core animation",
        startedAt: yesterdayISO(10, 0),
        endedAt: yesterdayISO(10, 32),
        duration: 32,
      },
      {
        id: uid(),
        projectId: verilog.id,
        task: "Verilog ALU overflow tests",
        startedAt: yesterdayISO(14, 0),
        endedAt: yesterdayISO(14, 20),
        duration: 20,
      },
    ],
    activeSession: null,
  };
}
