// Confidence levels per lifecycle status
export const CONFIDENCE_PERSON_OBSERVED = 0.2;
export const CONFIDENCE_RELATIONSHIP_IDENTIFIED = 0.5;
export const CONFIDENCE_RELATIONSHIP_UNDERSTOOD = 0.7;
export const CONFIDENCE_RELATIONSHIP_REFINED = 0.85;
export const CONFIDENCE_RELATIONSHIP_EVOLVED = 0.9;
export const CONFIDENCE_RELATIONSHIP_ARCHIVED = 0.3;
export const CONFIDENCE_RELATIONSHIP_VERIFIED = 1.0;

// Initial values
export const INITIAL_RELATIONSHIP_SIGNIFICANCE = 3;
