import { ReasoningCollection, ReasoningResult } from "./types";

/**
 * ReasoningAssemblyService
 *
 * Responsibilities:
 * Accepts a ReasoningCollection from ReasoningEngine and packages it into the official
 * public output contract (ReasoningResult) for downstream cognitive capabilities.
 *
 * Packaging Rules:
 * - Preserves exact artifact ordering generated by ReasoningEngine (no sorting, filtering, deduplication, or ranking).
 * - Reuses existing Reasoning object instances directly (no recreation, cloning, or property transformation).
 * - Immutability: Returns a runtime-frozen ReasoningResult object containing a frozen items array.
 * - Pure packaging layer only: no interpretation, merging, or summarization.
 */
export class ReasoningAssemblyService {
  public assemble(collection: ReasoningCollection): ReasoningResult {
    if (!collection) {
      throw new Error("ReasoningCollection is required");
    }

    const items = collection.reasoning ? collection.reasoning : Object.freeze([]);

    return Object.freeze({
      items: Object.isFrozen(items) ? items : Object.freeze([...items]),
    });
  }
}
