// Knowledge status confidence baselines
export const KNOWLEDGE_OBSERVED_CONFIDENCE = 0.3;
export const KNOWLEDGE_INFERRED_CONFIDENCE = 0.5;
export const KNOWLEDGE_REFINED_CONFIDENCE = 0.75;
export const KNOWLEDGE_REINFORCED_CONFIDENCE = 0.9;
export const KNOWLEDGE_UPDATED_CONFIDENCE = 0.85;
export const KNOWLEDGE_DEPRECATED_CONFIDENCE = 0.1;
export const KNOWLEDGE_VERIFIED_CONFIDENCE = 1.0;
