export const Events = {
  PROJECT_CREATED: "project.created",
  PROJECT_UPDATED: "project.updated",
  PROJECT_CONTINUED: "project.continued",
  PROJECT_DELETED: "project.deleted",
  TASK_CREATED: "task.created",
  TASK_COMPLETED: "task.completed",
  TASK_UPDATED: "task.updated",
  TASK_DELETED: "task.deleted",
  MISSION_COMPLETED: "mission.completed",
  NOTE_CREATED: "note.created",
  NOTE_EDITED: "note.edited",
  NOTE_DELETED: "note.deleted",
  SESSION_STARTED: "session.started",
  SESSION_ENDED: "session.ended",
  PRESENCE_UPDATED: "presence.updated",
  VAULT_FILE_UPLOADED: "vault.file.uploaded",
  VAULT_FILE_RENAMED: "vault.file.renamed",
  VAULT_FILE_MOVED: "vault.file.moved",
  VAULT_FILE_DELETED: "vault.file.deleted",
  VAULT_FILE_RESTORED: "vault.file.restored",
  VAULT_FOLDER_CREATED: "vault.folder.created",
  VAULT_FOLDER_DELETED: "vault.folder.deleted",
  VAULT_FOLDER_MOVED: "vault.folder.moved",
  IDENTITY_NODE_CREATED: "identity.node.created",
  IDENTITY_NODE_UPDATED: "identity.node.updated",
  IDENTITY_NODE_DELETED: "identity.node.deleted",
  IDENTITY_EDGE_CREATED: "identity.edge.created",
  IDENTITY_EDGE_DELETED: "identity.edge.deleted",
  IDENTITY_CREATED: "identity.created",
  IDENTITY_UPDATED: "identity.updated",
  IDENTITY_EVIDENCE_CREATED: "identity.evidence.created",
  IDENTITY_EVIDENCE_UPDATED: "identity.evidence.updated",
  IDENTITY_EVIDENCE_DELETED: "identity.evidence.deleted",
  IDENTITY_EVIDENCE_LINKED: "identity.evidence.linked",
  IDENTITY_EVIDENCE_UNLINKED: "identity.evidence.unlinked",
  IDENTITY_CONFIDENCE_CALCULATED: "identity.confidence.calculated",
  IDENTITY_CONFIDENCE_UPDATED: "identity.confidence.updated",
  IDENTITY_VERSION_CREATED: "identity.version.created",
  IDENTITY_SNAPSHOT_CREATED: "identity.snapshot.created",
  IDENTITY_TIMELINE_UPDATED: "identity.timeline.updated",
  IDENTITY_INTEREST_CREATED: "identity.interest.created",
  IDENTITY_INTEREST_UPDATED: "identity.interest.updated",
  IDENTITY_INTEREST_ARCHIVED: "identity.interest.archived",
  IDENTITY_SKILL_CREATED: "identity.skill.created",
  IDENTITY_SKILL_UPDATED: "identity.skill.updated",
  IDENTITY_SKILL_ARCHIVED: "identity.skill.archived",
  IDENTITY_GOAL_CREATED: "identity.goal.created",
  IDENTITY_GOAL_UPDATED: "identity.goal.updated",
  IDENTITY_GOAL_ARCHIVED: "identity.goal.archived",
  IDENTITY_HABIT_CREATED: "identity.habit.created",
  IDENTITY_HABIT_UPDATED: "identity.habit.updated",
  IDENTITY_HABIT_ARCHIVED: "identity.habit.archived",
  IDENTITY_PREFERENCE_CREATED: "identity.preference.created",
  IDENTITY_PREFERENCE_UPDATED: "identity.preference.updated",
  IDENTITY_PREFERENCE_ARCHIVED: "identity.preference.archived",
  IDENTITY_VALUE_CREATED: "identity.value.created",
  IDENTITY_VALUE_UPDATED: "identity.value.updated",
  IDENTITY_VALUE_ARCHIVED: "identity.value.archived",
  IDENTITY_RELATIONSHIP_CREATED: "identity.relationship.created",
  IDENTITY_RELATIONSHIP_UPDATED: "identity.relationship.updated",
  IDENTITY_RELATIONSHIP_ARCHIVED: "identity.relationship.archived",
  IDENTITY_PERSONALITY_CREATED: "identity.personality.created",
  IDENTITY_PERSONALITY_UPDATED: "identity.personality.updated",
  IDENTITY_PERSONALITY_ARCHIVED: "identity.personality.archived",
} as const;

export type DomainEventName = (typeof Events)[keyof typeof Events];

export interface DomainEvent<T = any> {
  name: DomainEventName;
  payload: T;
  timestamp: string;
}
