export const CONFIDENCE_SESSION_FINALIZED = 0.5;
export const CONFIDENCE_COLLECT_CONTEXTS = 0.6;
export const CONFIDENCE_ANALYZE_EVIDENCE = 0.7;
export const CONFIDENCE_GENERATE_REFLECTION = 0.8;
export const CONFIDENCE_REFLECTION_FINALIZED = 0.95;
export const CONFIDENCE_REFLECTION_ARCHIVED = 1.0;
