export const CONFIDENCE_SILENCE = 1.0;
export const CONFIDENCE_SUGGESTION = 0.7;
export const CONFIDENCE_QUESTION = 0.65;
export const CONFIDENCE_REMINDER = 0.8;
export const MIN_CONFIDENCE_FOR_PROACTIVE_INITIATIVE = 0.75;
